### ISSUE TITLE
Crash in Gen 1 Poison

### ISSUE THREAD

**Issue by naten2006** [Zarel/Pokemon-Showdown#2010]
When Gen 1 CC is done, the following error is showing up in our logs.

TypeError: Cannot read property 'counter' of undefined
    at Tools.exports.BattleStatuses.psn.onAfterMoveSelf (/srv/pokemon-showdown/mods/gen1/statuses.js:103:104)
    at Tools.Battle.runEvent (/srv/pokemon-showdown/battle-engine.js:2297:38)
    at Tools.exports.BattleScripts.runMove (/srv/pokemon-showdown/mods/gen1/scripts.js:118:9)
    at Tools.Battle.runDecision (/srv/pokemon-showdown/battle-engine.js:3640:9)
    at Tools.Battle.go (/srv/pokemon-showdown/battle-engine.js:3813:9)
    at Tools.Battle.commitDecisions (/srv/pokemon-showdown/battle-engine.js:3893:8)
    at Tools.Battle.choose (/srv/pokemon-showdown/battle-engine.js:3874:9)
    at Tools.Battle.receive (/srv/pokemon-showdown/battle-engine.js:4370:9)
    at process.<anonymous> (/srv/pokemon-showdown/battle-engine.js:123:12)
    at emitTwo (events.js:87:13)

Additional information:
message = battle-gen1challengecup-77|choose|p2|move 2|12
currentRequest = move

It looks like the counter var might not have been defined for gen 1.

**Comment by Joimer** [comment]
I'm taking a look at this.
