### ISSUE TITLE
Issue with Installation on remote server

### ISSUE THREAD

**Issue by futuresushi** [Zarel/Pokemon-Showdown#4635]
Hello! I'm attempting to host a server on my own web space and I am having trouble with npm during the installation. For reference: 

[agrius ~/www/noisespace.xyz/public_html/Pokemon-Showdown/_server] node -v
v8.4.0
[agrius ~/www/noisespace.xyz/public_html/Pokemon-Showdown/_server] npm -v
5.3.0

**So I have all the files downloaded and go to run the server and I run into the following issue:**

```
[agrius ~/www/noisespace.xyz/public_html/Pokemon-Showdown/_server] node pokemon-showdown 8000
Installing dependencies...
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /media/sdp/futuresushi/.npm/_logs/2018-04-29T16_48_53_760Z-debug.log
child_process.js:634
    throw err;
    ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/media/sdp/futuresushi/www/noisespace.xyz/public_html/Pokemon-Showdown/_server/pokemon-showdown:38:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

**Trying again with the alternate command:** 

```
[agrius ~/www/noisespace.xyz/public_html/Pokemon-Showdown/_server] node ./pokemon-showdown
Installing dependencies...
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /media/sdp/futuresushi/.npm/_logs/2018-04-29T16_50_26_768Z-debug.log
child_process.js:634
    throw err;
    ^

Error: Command failed: npm install --production
    at checkExecSyncError (child_process.js:591:13)
    at Object.execSync (child_process.js:631:13)
    at Object.<anonymous> (/media/sdp/futuresushi/www/noisespace.xyz/public_html/Pokemon-Showdown/_server/pokemon-showdown:38:16)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
```

I'm a little stumped. If there's something I need to get fixed server side with npm I'd need some specific details to pass on to my hosts since I don't get perfect admin access. Also attached logs for reference

[2018-04-29T16_50_26_768Z-debug.log](https://github.com/Zarel/Pokemon-Showdown/files/1958970/2018-04-29T16_50_26_768Z-debug.log)
[2018-04-29T16_48_53_760Z-debug.log](https://github.com/Zarel/Pokemon-Showdown/files/1958971/2018-04-29T16_48_53_760Z-debug.log)

**Comment by Zarel** [comment]
That looks to be an npm error, not a PS error. What happens if you just directly run `npm install`?

**Comment by futuresushi** [comment]
Yeah that looks to be the case. npm-dependent programs don't seem to like to play nice when it's not the exact specific version, but my npm in general seems a bit buggy, since

```
[agrius ~/www/noisespace.xyz/public_html/Pokemon-Showdown/_server] npm install
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /media/sdp/futuresushi/.npm/_logs/2018-04-29T19_26_33_001Z-debug.log
```

this happens

**Comment by Zarel** [comment]
I think you can get around this by running `npm install` on a different Linux computer, and then just deleting the `node_modules` folder on your server (if it exists) and copy/pasting the `node_modules` folder from your successful installation.

**Comment by Zarel** [comment]
You could also try a different package manager, like `yarn` or `pnpm`. As long as your `node_modules` folder is set up correctly, launching with `./pokemon-showdown` should work fine.

**Comment by scheibo** [comment]
Closing as obsolete, please reopen if you still are experiencing issues
