### ISSUE TITLE
Identifier 'Dex' has already been declared

### ISSUE THREAD

**Issue by race421** [Zarel/Pokemon-Showdown#4729]
botuser@toysever:~/Pokemon-Showdown$ nodejs pokemon-showdown 8000
/home/botuser/Pokemon-Showdown/pokemon-showdown:123
                        const Dex = require('./sim/dex');
                        ^

SyntaxError: Identifier 'Dex' has already been declared
    at Object.<anonymous> (/home/botuser/Pokemon-Showdown/pokemon-showdown:1:11)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

**Comment by race421** [comment]
update I am getting that same error on a lot of variable names well so far streams and stdin as well

**Comment by Zarel** [comment]
Anyway, your problem is that you installed Node from repositories. Repositories only offer incredibly outdated versions of Node.

Do this:

```
npm i -g n
n latest
./pokemon-showdown 8000
```
