### ISSUE TITLE
[Gen 4] Custap Berry + Trump Card  interaction causes a crash

### ISSUE THREAD

**Issue by scheibo** [Zarel/Pokemon-Showdown#5393]
```
 TypeError: Cannot read property 'pp' of null
    at Battle.basePowerCallback (/Pokemon-Showdown/data/moves.js:18263:21)
    at Battle.getDamage (/Pokemon-Showdown/.sim-dist/battle.js:1953:39)
    at Battle.getSpreadDamage (/Pokemon-Showdown/data/scripts.js:806:25)
    at Battle.spreadMoveHit (/Pokemon-Showdown/data/scripts.js:755:17)
    at Battle.hitStepMoveHitLoop (/Pokemon-Showdown/data/scripts.js:653:37)
    at Battle.trySpreadMoveHit (/Pokemon-Showdown/data/scripts.js:338:26)
    at Battle.useMoveInner (/Pokemon-Showdown/data/scripts.js:248:22)
    at Battle.useMove (/Pokemon-Showdown/data/scripts.js:138:25)
    at Battle.runMove (/Pokemon-Showdown/data/scripts.js:93:31)
    at Battle.runAction (/Pokemon-Showdown/.sim-dist/battle.js:2552:9)
```

See [input log](https://gist.githubusercontent.com/scheibo/84a7cc5ab30ac1e3723d434282abd7e7/raw/c38859c56c213d65467432e50b60cd5dcb628874/error.log) to repro.

*Yay! My smoke test works!*

**Comment by Slayer95** [comment]
Looks like Custap Berry should be removed from the possible ``sourceEffect`` values of moves, just like Instruct is in ``useMoveInner()``
